version: '3'
volumes:                           # ※ホストOSで永続化
    postgres_data:
        driver: 'local'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: "postgres_db"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: testDb
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data    # ※ホストOSで永続化
      - ./postgres/sql:/docker-entrypoint-initdb.d
